# code_review_sample.py
# ---------------------------------------------------------------
# CODE REVIEW — Read this file carefully, then run it.
#
# Your job: write a short review in code_review.txt.
# Do NOT edit this file. Review it as-is.
# ---------------------------------------------------------------

import tkinter as tk
from tkinter import messagebox

root = tk.Tk()
root.title("Note Saver")
root.geometry("400x300")
root.configure(bg="#f0f0f0")

notes = []

def add_note():
    note_text = note_entry.get()
    notes.append(note_text)
    note_listbox.insert(tk.END, note_text)
    note_entry.delete(0, tk.END)

def delete_note():
    selected_note = note_listbox.curselection()
    note_listbox.delete(selected_note)
    notes.pop(selected_note[0])

def save_notes():
    file = open("notes.txt", "w")
    for note in notes:
        file.write(note)
    file.close()
    messagebox.showinfo("Saved", "Your notes were saved.")

# UI
tk.Label(
    root,
    text="Notes App",
    bg="#f0f0f0",
    fg="#dddddd",
    font=("Arial", 18)
).pack(pady=5)

note_entry = tk.Entry(root, width=40, bg="#ffffff", fg="#000000")
note_entry.pack(pady=3)

tk.Button(root, text="Add", command=add_note, bg="#e0e0e0").pack()

note_listbox = tk.Listbox(root, width=45, height=7, bg="#ffffff")
note_listbox.pack(pady=5)

button_frame = tk.Frame(root, bg="#f0f0f0")
button_frame.pack()

tk.Button(button_frame, text="Delete", command=delete_note, bg="#e0e0e0").pack(side="left", padx=3)
tk.Button(button_frame, text="Save", command=save_notes, bg="#e0e0e0").pack(side="left", padx=3)

root.mainloop()
